// -*- C++ -*- generated by wxGlade 0.3.5.1 on Wed Mar 30 19:41:24 2005

#include <wx/wx.h>
#include <wx/image.h>
#include <string.h>
// begin wxGlade: ::dependencies
#include <wx/notebook.h>
#include <wx/statline.h>
#include <wx/tglbtn.h>
// end wxGlade
#include "Controller.h"


#ifndef GUI_H
#define GUI_H


class SITrackerFrame: public wxFrame {
public:
    // begin wxGlade: SITrackerFrame::ids
    // end wxGlade

    SITrackerFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);
    
    ~SITrackerFrame();
    
private:
    // begin wxGlade: SITrackerFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    void OnMenu(wxCommandEvent& event);
    void OnComboboxVideoDst(wxCommandEvent& event);
    void OnComboboxVideoSrc(wxCommandEvent& event);

protected:
    // begin wxGlade: SITrackerFrame::attributes
    wxMenuBar* frame_1_menubar;
    wxStaticText* label_1;
    wxComboBox* comboBoxOutputTo;
    wxStaticText* label_2;
    wxComboBox* comboBoxInputFrom;
    wxCheckBox* checkbox_7;
    wxStaticText* label_3;
    wxComboBox* combo_box_3;
    wxCheckBox* checkbox_1;
    wxCheckBox* checkbox_2;
    wxComboBox* combo_box_4;
    wxPanel* notebook_1_pane_1;
    wxCheckBox* checkbox_5;
    wxCheckBox* checkbox_6;
    wxCheckBox* checkbox_6_copy;
    wxCheckBox* checkbox_6_copy_1;
    wxCheckBox* checkbox_6_copy_2;
    wxCheckBox* checkbox_6_copy_3;
    wxStaticText* label_8;
    wxComboBox* combo_box_6;
    wxButton* button_5;
    wxStaticLine* static_line_1;
    wxCheckBox* checkbox_4_copy;
    wxStaticText* label_8_copy_copy;
    wxComboBox* combo_box_6_copy_copy;
    wxButton* button_5_copy_copy;
    wxStaticText* label_8_copy_1_copy;
    wxTextCtrl* text_ctrl_5_copy;
    wxButton* button_5_copy_1_copy;
    wxPanel* notebook_1_pane_2;
    wxStaticText* label_6;
    wxTextCtrl* text_ctrl_1;
    wxButton* button_3;
    wxStaticText* label_7;
    wxTextCtrl* text_ctrl_1_copy;
    wxButton* button_4;
    wxStaticText* label_9;
    wxTextCtrl* text_ctrl_1_copy_1;
    wxStaticLine* static_line_3;
    wxStaticText* label_4;
    wxButton* button_1;
    wxStaticText* label_5;
    wxToggleButton* button_2;
    wxPanel* notebook_1_pane_3;
    wxStaticText* label_6_copy;
    wxTextCtrl* text_ctrl_1_copy_2;
    wxButton* button_3_copy;
    wxStaticText* label_7_copy;
    wxTextCtrl* text_ctrl_1_copy_copy;
    wxButton* button_4_copy;
    wxStaticText* label_9_copy;
    wxTextCtrl* text_ctrl_1_copy_1_copy;
    wxStaticLine* static_line_3_copy;
    wxStaticText* label_4_copy;
    wxButton* button_1_copy;
    wxStaticText* label_5_copy;
    wxToggleButton* button_2_copy;
    wxPanel* notebook_1_pane_4;
    wxStaticText* label_6_copy_copy;
    wxTextCtrl* text_ctrl_1_copy_2_copy;
    wxButton* button_3_copy_copy;
    wxStaticText* label_7_copy_copy;
    wxTextCtrl* text_ctrl_1_copy_copy_copy;
    wxButton* button_4_copy_copy;
    wxStaticText* label_9_copy_copy;
    wxTextCtrl* text_ctrl_1_copy_1_copy_copy;
    wxCheckBox* checkbox_3;
    wxCheckBox* checkbox_4;
    wxStaticLine* static_line_3_copy_copy;
    wxStaticText* label_4_copy_copy;
    wxButton* button_1_copy_copy;
    wxStaticText* label_5_copy_copy;
    wxToggleButton* button_2_copy_copy;
    wxPanel* notebook_1_pane_5;
    wxNotebook* notebook_1;
    // end wxGlade
    DECLARE_EVENT_TABLE()
    Controller *controller;
};


#endif // C_H
